### ISSUE TITLE
ちらしとかポスター的なもの

### ISSUE THREAD

**Issue by K90j1** [LeapMotionDeveloperJp/MakerFaire-BoxingRobot#2]
ロボット説明とガッチャンコでもよいかも
あとLeapDevJpの案内も入れたいですね

**Comment by K90j1** [comment]
名刺も安いんでいいかもしれないです

**Comment by ega1979** [comment]
デザインはやりますね。
名刺、チラシは予算次第だと思うので、見積もりを何パターンかとってみます。
決定後デザインに入ります。

展示／配布用

**Comment by K90j1** [comment]
外観デザインてきなの

**Comment by K90j1** [comment]
いったんしめちゃいます
