### ISSUE TITLE
LeapMotionで動かすボクシングロボット　アルディーノ（ラズパイ）のプログラム

### ISSUE THREAD

**Issue by K90j1** [LeapMotionDeveloperJp/MakerFaire-BoxingRobot#5]
node.jsでリープモーションを受信する場合

**Comment by K90j1** [comment]
ラズパイのプログラムかきます

**Comment by ega1979** [comment]
まずは、ふつうのArduino IDEで一回組んでみます（感じをつかみたいので）。
その後でjohnny-fiveというarduino用のnode.jsモジュールがあるので移行します。
■jonny-five
https://github.com/rwaldron/johnny-five

（参考）電子回路を作る基礎を学びNode.jsでボードを操ろう
http://www.atmarkit.co.jp/ait/articles/1406/23/news026.html

**Comment by K90j1** [comment]
右手を出したら右パンチとかでいいですんかね？？
前進どうするか決めたいですね！

**Comment by K90j1** [comment]
ラズパイはwebiopiでなんかすぐ電圧たかくなるらしんで、ブレットボードとテスターの取り寄せ待ちです！！

**Comment by K90j1** [comment]
ユースケースの確認ですけど、こんな感じでよかったですかね？？
・右パンチの方法
　ユーザの右手をリープモーションが認識させる
　疑問：時間は何秒間にしますか？
・右パンチ２回の方法
　ユーザの右手をリープモーションが認識させる。右手をリープの認識外にする。また右手をリープに認識させる
・左パンチ
　同上

**Comment by K90j1** [comment]
いったんしめちゃいます
