### ISSUE TITLE
LeapMotionで動かすボクシングロボット　台（リング）

### ISSUE THREAD

**Issue by K90j1** [LeapMotionDeveloperJp/MakerFaire-BoxingRobot#6]
リングは欲しいですね。作品ができた後でつくりましょう！

**Comment by ega1979** [comment]
ジオラマですかね。以下みたいのを作りましょう。

■カミロボのリングを作ってみよう
http://www.kami-robo.com/ja/ring/

■サイズ
最低60cm*60cm

**Comment by K90j1** [comment]
ぉおガチっすね

**Comment by K90j1** [comment]
いったんしめちゃいます
